import React from 'react';
import { View, Text, StyleSheet, Image } from '@react-pdf/renderer';

// Stoodiora branded PDF styles
export const stoodioraStyles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 30,
    fontFamily: 'Helvetica',
    fontSize: 10,
    lineHeight: 1.6,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#c4b28d',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: 80,
    height: 40,
    marginRight: 15,
    objectFit: 'contain',
  },
  brandInfo: {
    flexDirection: 'column',
  },
  companyName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#c4b28d',
    marginBottom: 2,
  },
  tagline: {
    fontSize: 10,
    color: '#6b7280',
    fontStyle: 'italic',
  },
  headerRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  supportLabel: {
    fontSize: 8,
    color: '#6b7280',
    marginBottom: 2,
  },
  supportInfo: {
    fontSize: 9,
    color: '#374151',
    fontWeight: 'medium',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#374151',
    marginBottom: 20,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 8,
    color: '#6b7280',
  },
  // Rest of the shared styles...
  documentId: {
    fontSize: 10,
    color: '#6b7280',
    marginBottom: 20,
    textAlign: 'center',
  },
  detailsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  column: {
    flex: 1,
    paddingRight: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#374151',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: 3,
    alignItems: 'flex-start',
  },
  detailLabel: {
    fontSize: 9,
    color: '#6b7280',
    width: 80,
    flexShrink: 0,
  },
  detailValue: {
    fontSize: 9,
    color: '#374151',
    flex: 1,
    fontWeight: 'medium',
  },
});

export const StoodioraPDFHeader: React.FC = () => (
  <View style={stoodioraStyles.header}>
    <View style={stoodioraStyles.headerLeft}>
      <Image 
        src="/images/stoodiora-logo.svg"
        style={stoodioraStyles.logo}
        cache={false}
      />
      <View style={stoodioraStyles.brandInfo}>
        <Text style={stoodioraStyles.companyName}>STOODIORA</Text>
        <Text style={stoodioraStyles.tagline}>Studio Management System</Text>
      </View>
    </View>
    <View style={stoodioraStyles.headerRight}>
      <Text style={stoodioraStyles.supportLabel}>Support Contact</Text>
      <Text style={stoodioraStyles.supportInfo}>team.stoodiora@gmail.com</Text>
      <Text style={stoodioraStyles.supportInfo}>+91 91064 03233</Text>
    </View>
  </View>
);

export const StoodioraPDFFooter: React.FC = () => (
  <View style={stoodioraStyles.footer}>
    <Text style={stoodioraStyles.footerText}>
      Generated by Stoodiora Studio Management System
    </Text>
    <Text style={stoodioraStyles.footerText}>
      stoodiora.com
    </Text>
  </View>
);
